version: '3.8'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=saide
      - DJANGO_SUPERUSER_EMAIL=saideomarsaid@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=123456

volumes:
  static_volume:
  media_volume: