# Generated by Django 5.1.4 on 2025-01-10 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronicle',
            options={'ordering': ['-date'], 'verbose_name': 'Crônica', 'verbose_name_plural': 'Crônicas'},
        ),
        migrations.AddField(
            model_name='chronicle',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Apenas superusuários podem criar crônicas', limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeaturedChronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pdf_file', models.FileField(help_text='Upload do arquivo PDF da crônica principal', upload_to='featured_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Apenas superusuários podem criar crônicas principais', limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crônica Principal',
                'verbose_name_plural': 'Crônicas Principais',
                'ordering': ['-date'],
            },
        ),
    ]
